# Generated by Django 4.2.5 on 2023-09-23 23:09

from django.db import migrations, models
import subjects.models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='credits',
            field=models.IntegerField(validators=[subjects.models.validar_numero_positivo]),
        ),
    ]
